pde_name: "1D_Diffusion-Reaction"
model_name: "UNet"
# mode
if_training: True
continue_training: False
model_path: null
# output args
output_dir: "./checkpoints/"
save_period: 20
# visualize
tensorboard: True
log_dir: "./logs/tensorboard/"
# training args
seed: 0
training_type: "autoregressive"
pushforward: True
initial_step: 10
unroll_step: 20
epochs: 500
# datasets args
dataset:
  single_file: True
  file_name: "ReacDiff_Nu0.5_Rho1.0.hdf5"
  saved_folder: "DATA_ROOT_PATH"
  reduced_resolution: 4
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# datasets args
dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: False
# dataloader args
model:
  in_channels: 1
  out_channels: 1
  init_features: 32
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# learning rate scheduler
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5