pde_name: "3D_Maxwell"
model_name: "UNet"
# mode
if_training: True
continue_training: False
model_path: null
# output args
output_dir: "./checkpoint/"
save_period: 1
# visualize
tensorboard: True
log_dir: "./logs/tensorboard/"
# training args
seed: 0
training_type: "autoregressive"
pushforward: False
initial_step: 2
unroll_step: 20
epochs: 1
# datasets args
dataset:
  single_file: False
  file_name: "3D_Maxwell_10_1.h5"
  saved_folder: "/home/data2/fluidbench/3D/Maxwell/"
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader args
dataloader:
  batch_size: 2
  num_workers: 1
  pin_memory: False
# model args
model:
  in_channels: 6
  out_channels: 6
  init_features: 32
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# learning rate scheduler
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5